### ISSUE TITLE
No access to raw .bnk files

### ISSUE THREAD

**Issue by mickael666** [djey47/tduf#1]
Hi,
I am having an issue with TDUF 1.12, which looks like this in my case:
![4658865b4d102d8ce4b214187d714497](https://user-images.githubusercontent.com/62466065/77224998-3dc1b880-6b6b-11ea-8736-dd0ae45a68fb.png)

I do not see the Kind / Path, etc. table to edit the raw .bnk files with each car slots. 
![unknown](https://user-images.githubusercontent.com/62466065/77225010-647fef00-6b6b-11ea-8130-7226b2f7f98e.png)

Any ideas?

Mickael

**Comment by djey47** [comment]
Hi,
issue transferred to TDUF repository as it does not seem to be linked to TDUCP. 

Something seems to prevent the plugin from loading correctly. Error details might be found in the logs files (under TDUF logs directory, DatabaseEditor.log).

Please attach this file here.

Thanks for your feedback @mickael666

**Comment by mickael666** [comment]
Hi,
Thanks for your quick answer. Indeed the issue seems related to plugin loading:

00:01  WARN: [MappingPlugin] No bnk1.map file was found under game directory: C:\Program Files (x86)\Atari\TDU Platinum\Euro\Bnk\DataBase
00:01  WARN: [MappingPlugin] Mapping plugin not loaded, no rendering will be performed
00:01  WARN: [MappingPlugin] Mapping plugin not loaded, no rendering will be performed

Even when I tried with bnk1.map file in both directories (Euro\Bnk & Euro\Bnk\Database), it does not seem to find it...

I tried as well resetting the database cache and app settings multiple times, with no success.

**Comment by djey47** [comment]
Please post contents of tduf configuration file:  C:\Users\YOU\.tduf\tduf.properties
Game path seems to be incorrect...

**Comment by mickael666** [comment]
Here it is:

#TDUF configuration
#Sat Mar 21 16:28:14 CET 2020
tduf.editor.locale=us
tduf.editor.profile=Vehicle slots
tdu.root.directory=C\:\\Program Files (x86)\\Atari\\TDU Platinum\\Euro\\Bnk\\DataBase
tdu.database.directory=C\:\\Program Files (x86)\\Atari\\TDU Platinum\\Euro\\Bnk\\DataBase

**Comment by mickael666** [comment]
Here it is:
#TDUF configuration
#Sat Mar 21 16:28:14 CET 2020
tduf.editor.locale=us
tduf.editor.profile=Vehicle slots
tdu.root.directory=C\:\\Program Files (x86)\\Atari\\TDU Platinum\\Euro\\Bnk\\DataBase
tdu.database.directory=C\:\\Program Files (x86)\\Atari\\TDU Platinum\\Euro\\Bnk\\DataBase

**Comment by djey47** [comment]
Yes, game folder  is an automatic guess. I may have a look to find the issue.

Anyway, glad it worked. Enjoy ^^

**Comment by djey47** [comment]
Note: after reading code again (finally after years...), I realized there's no automatic guess for game folder from database folder. They have to be given separately :
- first time, when browsing database location
- then game location is asked once when loading database.

Database location can be easily changed via current UI, but not game location.
Only way is to either reset settings or modify tduf.properties file manually.

Changing all TDUF settings via UI would be available as a common feature. Another feature could be to check if game location given is valid, as well.
But they won't be ready anytime soon.

Sorry for incovenience.
