### ISSUE TITLE
Editor failed, can't continue

### ISSUE THREAD

**Issue by slrslr** [djey47/tduf#5]
Hello,

i need to supply log file mentioned on image or is using wrong Java version?

![](https://i.postimg.cc/QCJZFLZv/tduf-cant-continue.jpg)

any suggestion please?

**Comment by djey47** [comment]
Hi, I'll need log file as described in message and a bit of context. When did the crash occur?

**Comment by slrslr** [comment]
Thank you for your reply. Unfortunately the person who have got this error not provided the log file, so we are in a dead end.
But he ended up launching the TDUF somehow anyway.
